<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AutoMapper" Version="16.1.1" />
    <PackageVersion Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.16" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="2.3.10" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.16" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Identity.Core" Version="9.0.16" />
    <PackageVersion Include="Microsoft.Extensions.Identity.Stores" Version="9.0.16" />
  </ItemGroup>
</Project>